### PR TITLE
[Major] Added support for PHP v7.3.

### PR DESCRIPTION
**Pull request by hopeseekr**
Also:
- [Major] Removed support for EOL'd PHP v5.6, v7.0 and HHVM :-(
- [Major] Upgraded from PHPUnit 4.5 to 6.5.
- Moved phpunit.xml to / to be in line with the standard PHP package layout
- [minor] Fixed the one Risky test.

---
This change is [Reviewable](https://reviewable.io/reviews/itafroma/zork-php/2)

### CODE REVIEW

**Comment by itafroma** [comment]
Thanks for your interest! As mentioned in the [README's development disclaimer](https://github.com/itafroma/zork-php#development-disclaimer), this is not a collaborative project, so I am not accepting any PRs at this time.

**Comment by hopeseekr** [comment]
Well, the good news is that I have now officially forked your repo and currently, so there's at least one instance that builds on current PHP and has been modified in the last 2+ years.

Cheers!

**Comment by hopeseekr** [comment]
Well, I was about to submit a PR for PHP 7.4 and 8.0 support...

But then I saw that this PR had been rejected, and saw your down right nasty response that "this project is not a collaborative effort."

So, whatever. Your version won't even run on modern PHP. I hope people find my fork and your work can go into the future solely via my hands.

**Comment by eswenson1** [comment]
@hopeseekr Thanks!  I don't understand that mentality.  As far as I'm concerned, yours is the fork/repo to use.  Thanks.

**Pull request closed without merging**
